const data = [
  {
    'id': 1,
    'name': 'Juan Cruz',
    'lastName': 'Cruz',
    'address': 'Sim, Cit, Shatin Street, Hongkong',
    'yearWorkOfExperience': '10 Years',
    'highestEducation': 'Bachelor Degree',
    'languageSkills': 'English, Mandarin, Cantonese',
    'currentEmployedStatus': 'Resigned',
    'currentSalary': '$7000',
    'expectedSalary': '$8000',
    'state': '1',
    'contactNumber': '+615 2930 020',
    'email': 'cruz@hotmail.com',
    'potentialScoreAI': '83',
    'mbti': 'INTP',
    'favorite': true
  },
  {
    'id': 2,
    'name': 'Mary Goode',
    'lastName': 'Goode',
    'address': 'Sim, Cit, Shatin Street, Hongkong',
    'yearWorkOfExperience': '4 Years',
    'highestEducation': 'Master Degree',
    'languageSkills': 'English, Mandarin, Cantonese',
    'currentEmployedStatus': 'Resigned',
    'currentSalary': '$5000',
    'expectedSalary': '$8000',
    'state': '2',
    'contactNumber': '+695 2130 020',
    'email': 'marygoode@gmail.com',
    'potentialScoreAI': '91',
    'mbti': 'ERP',
    'favorite': false
  },
  {
    'id': 3,
    'name': 'Shaby Deo',
    'lastName': 'Deo',
    'address': 'Sim, Cit, Shatin Street, Hongkong',
    'yearWorkOfExperience': '12 Years',
    'highestEducation': 'Bachelor Degree',
    'languageSkills': 'Cantonese',
    'currentEmployedStatus': 'Resigned',
    'currentSalary': '$2000',
    'expectedSalary': '$3000',
    'state': '3',
    'contactNumber': '+415 1234 020',
    'email': 'deo@yahoo.com',
    'potentialScoreAI': '87',
    'mbti': 'ABCD',
    'favorite': false
  },
  {
    'id': 4,
    'name': 'Kyo Gee',
    'lastName': 'Gee',
    'address': 'Sim, Cit, Shatin Street, Hongkong',
    'yearWorkOfExperience': '5 Years',
    'highestEducation': 'Bachelor Degree',
    'languageSkills': 'Mandarin, Cantonese',
    'currentEmployedStatus': 'Resigned',
    'currentSalary': '$5200',
    'expectedSalary': '$8000',
    'state': '4',
    'contactNumber': '+615 2930 020',
    'email': 'kyogee@hotmail.com',
    'potentialScoreAI': '83',
    'mbti': 'ENTI',
    'favorite': true
  },
  {
    'id': 5,
    'name': 'John Lee',
    'lastName': 'Lee',
    'address': 'Sim, Cit, Shatin Street, Hongkong',
    'yearWorkOfExperience': '3 Years',
    'highestEducation': 'Master Degree',
    'languageSkills': 'English, Cantonese',
    'currentEmployedStatus': 'Resigned',
    'currentSalary': '$7000',
    'expectedSalary': '$8000',
    'state': '5',
    'contactNumber': '+615 2930 123',
    'email': 'lee@hotmail.com',
    'potentialScoreAI': '88',
    'mbti': 'XXXX',
    'favorite': true
  },
  {
    'id': 6,
    'name': 'Kyo Dee',
    'lastName': 'Dee',
    'address': 'Sim, Cit, Shatin Street, Hongkong',
    'yearWorkOfExperience': '2 Years',
    'highestEducation': 'Bachelor Degree',
    'languageSkills': 'Mandarin, Cantonese',
    'currentEmployedStatus': 'Resigned',
    'currentSalary': '$1000',
    'expectedSalary': '$2000',
    'state': '1',
    'contactNumber': '+615 4321 123',
    'email': 'dee@hotmail.com',
    'potentialScoreAI': '87',
    'mbti': 'INTP',
    'favorite': false
  },
]

export default data